name: CI/CD Pipeline for Eureka Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests with Maven
        # The 'verify' command compiles, runs tests, and packages the application.
        # This is more efficient than running 'install' and 'test' separately.
        run: mvn -B -f eurekaserver/pom.xml verify

  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    # This job will only start after the 'build-and-test' job succeeds
    needs: build-and-test
    # IMPORTANT: This job will only run on a push to the 'main' branch, not for pull requests.
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        # This action sets up a more powerful Docker builder.
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        # This securely logs into Docker Hub using the secrets you created.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        # This is the official Docker action for building and pushing images.
        uses: docker/build-push-action@v5
        with:
          # 'context' tells Docker where to find the Dockerfile and source code.
          context: ./eurekaserver
          # 'push' tells the action to actually push the image after building.
          push: true
          # 'tags' defines the name and tags for your image.
          # This will create and push two tags: 'latest' and '1.0.0'.
          # It uses your DOCKER_USERNAME secret to construct the correct repository name.
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/microservicebasedapp-eurekaserver:latest
            ${{ secrets.DOCKER_USERNAME }}/microservicebasedapp-eurekaserver:1.0.0
