name: CI/CD Pipeline for User Service

on:
  # This workflow starts after the Eureka Server workflow is successfully completed on the main branch.
  workflow_run:
    workflows: ["CI/CD Pipeline for Eureka Server"]
    types:
      - completed
  
  # Also allow manual triggering for debugging.
  workflow_dispatch:

jobs:
  # This job checks if the triggering workflow was successful before proceeding.
  check-eureka-build:
    name: Check Eureka Workflow Status
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Eureka Server workflow succeeded
        run: echo "Eureka Server CI/CD completed successfully. Proceeding with User Service."
  
  build-and-test:
    name: Build and Test User Service
    runs-on: ubuntu-latest
    # This job only runs if the check job succeeds.
    needs: check-eureka-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests with Maven
        run: mvn -B -f userservice/pom.xml verify

  build-and-push-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: build-and-test
    # This job also only runs if the triggering workflow was a success.
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./userservice
          file: ./userservice/Dockerfile
          push: true
          # Define clear and consistent tags for your image.
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/microservicebasedapp-userservice:latest
            ${{ secrets.DOCKER_USERNAME }}/microservicebasedapp-userservice:1.0.0
